services:
  therapist_agent_dev:
    image: docker.theten.ai/ten-framework/ten_agent_build:0.6.11
    #image: ghcr.io/ten-framework/ten_agent_build:0.6.11
    container_name: therapist_agent_dev
    platform: linux/amd64
    tty: true
    stdin_open: true
    restart: always
    command: ["/app/start-servers.sh"]
    ports:
      - "${GRAPH_DESIGNER_SERVER_PORT:-49483}:${GRAPH_DESIGNER_SERVER_PORT:-49483}"
      - "${SERVER_PORT:-8080}:${SERVER_PORT:-8080}"
    volumes:
      - ./:/app
      - ${LOG_PATH:-/tmp/ten_logs}:/tmp/ten_logs
      - ../.vscode/:/app/.vscode
    working_dir: /app
    env_file:
      - .env
    networks:
      - therapist_agent_network

  therapist_agent_demo:
    image: ghcr.io/ten-framework/ten_agent_demo:0.10.6-19-g8ecacde4
    container_name: therapist_agent_demo
    restart: always
    ports:
      - "3002:3000"
    networks:
      - therapist_agent_network
    environment:
      - AGENT_SERVER_URL=http://therapist_agent_dev:8080

networks:
  therapist_agent_network:
    driver: bridge